# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/ishara/Data/MAS/measurement_detection/new/core/build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/ishara/Data/MAS/measurement_detection/new

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ishara/Data/MAS/measurement_detection/new/CMakeFiles /media/ishara/Data/MAS/measurement_detection/new/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ishara/Data/MAS/measurement_detection/new/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kitty

# Build rule for target.
kitty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kitty
.PHONY : kitty

# fast build rule for target.
kitty/fast:
	$(MAKE) -f CMakeFiles/kitty.dir/build.make CMakeFiles/kitty.dir/build
.PHONY : kitty/fast

#=============================================================================
# Target rules for targets named corner

# Build rule for target.
corner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 corner
.PHONY : corner

# fast build rule for target.
corner/fast:
	$(MAKE) -f CMakeFiles/corner.dir/build.make CMakeFiles/corner.dir/build
.PHONY : corner/fast

corner.o: corner.cpp.o

.PHONY : corner.o

# target to build an object file
corner.cpp.o:
	$(MAKE) -f CMakeFiles/corner.dir/build.make CMakeFiles/corner.dir/corner.cpp.o
.PHONY : corner.cpp.o

corner.i: corner.cpp.i

.PHONY : corner.i

# target to preprocess a source file
corner.cpp.i:
	$(MAKE) -f CMakeFiles/corner.dir/build.make CMakeFiles/corner.dir/corner.cpp.i
.PHONY : corner.cpp.i

corner.s: corner.cpp.s

.PHONY : corner.s

# target to generate assembly for a file
corner.cpp.s:
	$(MAKE) -f CMakeFiles/corner.dir/build.make CMakeFiles/corner.dir/corner.cpp.s
.PHONY : corner.cpp.s

kitty.o: kitty.cpp.o

.PHONY : kitty.o

# target to build an object file
kitty.cpp.o:
	$(MAKE) -f CMakeFiles/kitty.dir/build.make CMakeFiles/kitty.dir/kitty.cpp.o
.PHONY : kitty.cpp.o

kitty.i: kitty.cpp.i

.PHONY : kitty.i

# target to preprocess a source file
kitty.cpp.i:
	$(MAKE) -f CMakeFiles/kitty.dir/build.make CMakeFiles/kitty.dir/kitty.cpp.i
.PHONY : kitty.cpp.i

kitty.s: kitty.cpp.s

.PHONY : kitty.s

# target to generate assembly for a file
kitty.cpp.s:
	$(MAKE) -f CMakeFiles/kitty.dir/build.make CMakeFiles/kitty.dir/kitty.cpp.s
.PHONY : kitty.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kitty"
	@echo "... corner"
	@echo "... corner.o"
	@echo "... corner.i"
	@echo "... corner.s"
	@echo "... kitty.o"
	@echo "... kitty.i"
	@echo "... kitty.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

